"""
Script to add Google Drive PDF links to the questions spreadsheet.
Uses a mapping file generated by the Google Apps Script.

Usage:
    1. Run the Google Apps Script to generate pdf_links_mapping.csv
    2. Download that CSV to this folder
    3. Run: python add_gdrive_links.py
"""

import pandas as pd
import re
from pathlib import Path

# Configuration
CSV_FILE = "ALL_PAPERS_COMBINED.csv"
GDRIVE_MAPPING_FILE = "pdf_links_mapping.csv"
OUTPUT_CSV = "ALL_PAPERS_WITH_GDRIVE_LINKS.csv"
OUTPUT_EXCEL = "ALL_PAPERS_WITH_GDRIVE_LINKS.xlsx"

def get_script_dir():
    return Path(__file__).parent.resolve()

def load_gdrive_mapping(mapping_file):
    """Load the Google Drive filename -> link mapping."""
    df = pd.read_csv(mapping_file)
    
    # Create lookup dict: (folder, filename) -> link
    mapping = {}
    for _, row in df.iterrows():
        # Use the shareable_link for viewing in browser
        key = (row['folder'], row['filename'])
        mapping[key] = row['shareable_link']
    
    print(f"Loaded {len(mapping)} Google Drive links")
    return mapping

def extract_paper_info(source_qp):
    """Extract paper code and session from source_qp."""
    if pd.isna(source_qp):
        return None, None
    
    match = re.search(r'8464(C\d[FH])', source_qp)
    paper_code = f"8464{match.group(1)}" if match else None
    
    session_match = re.search(r'(NOV|JUN|OCT)(\d{2})', source_qp, re.IGNORECASE)
    session = f"{session_match.group(1).upper()}{session_match.group(2)}" if session_match else None
    
    return paper_code, session

def extract_subquestion_number(subquestion_id):
    """Extract subquestion number from various formats."""
    if pd.isna(subquestion_id):
        return None
    
    subq_str = str(subquestion_id)
    
    match = re.search(r'Q\d+\.(\d+)', subq_str)
    if match:
        return int(match.group(1))
    
    match = re.search(r'\d+\.(\d+)', subq_str)
    if match:
        return int(match.group(1))
    
    return None

def find_pdf_filename(row):
    """
    Generate the expected PDF filename for a row.
    Returns (folder_name, filename) tuple.
    """
    paper_code, session = extract_paper_info(row['source_qp'])
    question_num = row['question_id']
    subq_num = extract_subquestion_number(row['subquestion_id'])
    
    if not paper_code or not session or pd.isna(question_num):
        return None, None
    
    question_num = int(question_num)
    folder_name = f"{paper_code}_question_pdfs"
    
    # Try different filename patterns that might exist
    possible_filenames = []
    
    # Pattern with subquestion: AQA-8464C1F-JUN22_Q01_1.pdf
    if subq_num:
        possible_filenames.append(f"AQA-{paper_code}-{session}_Q{question_num:02d}_{subq_num}.pdf")
        possible_filenames.append(f"AQA-{paper_code}-{session}_QQ{question_num:02d}_{subq_num}.pdf")  # Double Q typo
        possible_filenames.append(f"AQA-{paper_code}-{session}-CR_Q{question_num:02d}_{subq_num}.pdf")  # With -CR
    
    # Pattern without subquestion: AQA-8464C1F-NOV20_Q01.pdf
    possible_filenames.append(f"AQA-{paper_code}-{session}_Q{question_num:02d}.pdf")
    possible_filenames.append(f"AQA-{paper_code}-{session}_QQ{question_num:02d}.pdf")  # Double Q typo
    possible_filenames.append(f"AQA-{paper_code}-{session}-CR_Q{question_num:02d}.pdf")  # With -CR
    
    # Simplified pattern: NOV21_Q01.pdf
    possible_filenames.append(f"{session}_Q{question_num:02d}.pdf")
    
    return folder_name, possible_filenames

def find_gdrive_link(row, gdrive_mapping):
    """Find the Google Drive link for a row."""
    folder_name, possible_filenames = find_pdf_filename(row)
    
    if not folder_name or not possible_filenames:
        return None
    
    # Try each possible filename
    for filename in possible_filenames:
        key = (folder_name, filename)
        if key in gdrive_mapping:
            return gdrive_mapping[key]
    
    return None

def save_excel_with_hyperlinks(df, output_path, url_column='question_pdf_link'):
    """Save DataFrame to Excel with clickable hyperlinks."""
    try:
        import openpyxl
        from openpyxl.styles import Font
        
        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = "Questions"
        
        headers = list(df.columns)
        for col_idx, header in enumerate(headers, 1):
            ws.cell(row=1, column=col_idx, value=header)
            ws.cell(row=1, column=col_idx).font = Font(bold=True)
        
        url_col_idx = headers.index(url_column) + 1 if url_column in headers else None
        
        for row_idx, row in enumerate(df.itertuples(index=False), 2):
            for col_idx, value in enumerate(row, 1):
                cell = ws.cell(row=row_idx, column=col_idx)
                
                if col_idx == url_col_idx and value and not pd.isna(value) and str(value).startswith('http'):
                    cell.hyperlink = str(value)
                    cell.value = "📄 Open PDF"
                    cell.font = Font(color="0563C1", underline="single")
                else:
                    cell.value = value if not pd.isna(value) else ""
        
        for col_idx, header in enumerate(headers, 1):
            ws.column_dimensions[openpyxl.utils.get_column_letter(col_idx)].width = min(50, max(12, len(str(header)) + 2))
        
        wb.save(output_path)
        print(f"Saved Excel with clickable hyperlinks: {output_path}")
        return True
        
    except ImportError:
        print("Note: Install openpyxl for Excel output: pip install openpyxl")
        return False

def main():
    base_dir = get_script_dir()
    
    print(f"Working directory: {base_dir}")
    
    # Check for mapping file
    mapping_path = base_dir / GDRIVE_MAPPING_FILE
    if not mapping_path.exists():
        print(f"\n❌ Error: Could not find '{GDRIVE_MAPPING_FILE}'")
        print("\nTo generate this file:")
        print("1. Upload your PDF folders to Google Drive")
        print("2. Run the Google Apps Script (see google_apps_script.js)")
        print("3. Download the generated 'pdf_links_mapping.csv' to this folder")
        print("4. Run this script again")
        return
    
    # Load mapping
    gdrive_mapping = load_gdrive_mapping(mapping_path)
    
    # Read questions CSV
    df = pd.read_csv(base_dir / CSV_FILE)
    print(f"Loaded {len(df)} rows from {CSV_FILE}")
    
    # Find links for each row
    print("Matching Google Drive links...")
    pdf_links = []
    matched = 0
    
    for idx, row in df.iterrows():
        link = find_gdrive_link(row, gdrive_mapping)
        pdf_links.append(link)
        if link:
            matched += 1
    
    df['question_pdf_link'] = pdf_links
    
    print(f"\nMatched: {matched}/{len(df)} rows")
    
    # Show unmatched samples for debugging
    unmatched_count = len(df) - matched
    if unmatched_count > 0:
        print(f"\nUnmatched: {unmatched_count} rows")
        unmatched = df[df['question_pdf_link'].isna()]
        print("Sample unmatched (first 5):")
        for idx, row in unmatched.head(5).iterrows():
            folder, filenames = find_pdf_filename(row)
            print(f"  Looking for: {folder}/{filenames[0] if filenames else 'N/A'}")
    
    # Save outputs
    csv_path = base_dir / OUTPUT_CSV
    df.to_csv(csv_path, index=False)
    print(f"\nSaved CSV: {csv_path}")
    
    excel_path = base_dir / OUTPUT_EXCEL
    save_excel_with_hyperlinks(df, excel_path)
    
    # Show sample links
    print("\nSample links (first 3 matched):")
    for link in [l for l in pdf_links if l][:3]:
        print(f"  {link}")

if __name__ == "__main__":
    main()
